### ISSUE TITLE
Any demo? 

### ISSUE THREAD

**Issue by hapishyguy** [eldertek/scovie#1]
Any demo?

**Comment by eldertek** [comment]
Hello, like a video ?

**Comment by hapishyguy** [comment]
No. Like a working model.

**Comment by eldertek** [comment]
Actually I need a server, I will try to find one but it is not expected

**Comment by hapishyguy** [comment]
Let me know and I can give my aws or google cloud. Are you on Discord?

**Comment by eldertek** [comment]
Yes I am eldertek#1146

**Comment by hapishyguy** [comment]
check discord

**Comment by eldertek** [comment]
Closing now, demo is available ! https://scovie.eclipse-technology.eu/
